# PYTHON_VERSION in ["3.7", "3.8", "3.9"]
ARG PYTHON_VERSION=3.8
# SOURCE in ["local", "github"]
ARG SOURCE=local

# Our base image is the official python image. If needed we can look into slimming this down.
FROM python:${PYTHON_VERSION} AS base
# ACCEPT_EULA is set for installing msodbcsql18
# We also hardcode we are on debian 11. If we wanted to generalize we could:
# apt install lsb-release
# and then s/11/$(lsb_release -rs)/
ENV ACCEPT_EULA=Y
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt update && \
    apt install default-jre unixodbc unixodbc-dev msodbcsql17 locales locales-all -y && \
    apt clean && \
    rm /etc/apt/sources.list.d/mssql-release.list
RUN python -m pip install --no-cache-dir --upgrade pip

FROM base as build_local
WORKDIR /great_expectations
COPY . .

FROM base AS build_github
# BRANCH is the branch name you want to build
ARG BRANCH=develop
RUN git clone --depth 1 --branch ${BRANCH} https://github.com/great-expectations/great_expectations.git
WORKDIR /great_expectations

FROM build_${SOURCE} AS dev
RUN pip install --no-cache-dir --requirement requirements-dev.txt --constraint constraints-dev.txt
RUN pip install .
CMD [ "python", "--version"]

FROM dev as test
RUN pip install --no-cache-dir --requirement requirements-dev-test.txt --constraint constraints-dev.txt

FROM test as azure
RUN pip install --no-cache-dir --requirement requirements-dev-test-pipeline.txt --constraint constraints-dev.txt
